name: Package-lock police

on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [ develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate lockfileVersion
        uses: mansona/npm-lockfile-version@v1
        with:
          version: 1
        
      - name: Check for eve
        # exits with 0 if grep found term, 1 if not
        run: grep -qc 'eve@git' package-lock.json; test $? -eq 0
