# Action to check for red flags in package-lock.json
# 1. lockfileVersion: must be 1
# 2. 'git+ssh' must not be present

name: Package-lock Police

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate lockfileVersion
        uses: mansona/npm-lockfile-version@v1
        with:
          version: 1

      - name: Check for bad protocol
        # exits with 0 if grep found term, 1 if not
        run: grep -qc 'git+ssh' package-lock.json; test $? -ne 0
